#!/bin/busybox sh

set -e
set -x
mount -t sysfs /sys /sys
mount -t proc /proc /proc
mount -t xenfs -o nodev /proc/xen /proc/xen

if test -e /sys/class/net/eth0; then
  ip link set eth0 address fe:ff:ff:ff:ff:fe
  ip addr flush eth0
  ip link set eth0 up
  brctl addbr br0
  brctl addif br0 eth0
  ip link set br0 up
else
  echo "No network interface named eth0."
  ls -l /sys/class/net/
fi

domid=$(/bin/xenstore-read "target")
vm_path=$(xenstore-read "/local/domain/$domid/vm")
dm_args=$(xenstore-read "$vm_path/image/dmargs")

/bin/qemu $dm_args
