#!/bin/bash

set -e
umask 022

cd "$(dirname "$0")/.."

rootfs_dir="$(pwd)/build/rootfs/dir"

rm -fr "$rootfs_dir"

# Using dracut to gather the shared libraries
# from https://dracut.wiki.kernel.org/index.php/Main_Page
if ! test -x "$DRACUT_INSTALL"; then
    echo DRACUT_INSTALL unset or incorrect >&2
    exit 1
fi

inst() {
    [[ -e "${rootfs_dir}/${2:-$1}" ]] && return 0  # already there
    "$DRACUT_INSTALL" -D "$rootfs_dir" -l "$@"
}

mkdir -p "$rootfs_dir"/{bin,etc,proc/xen,sys,dev,tmp}

echo "Building initrd in $rootfs_dir"
inst build/busybox/busybox /bin/busybox
for i in \
    brctl \
    cat \
    cut \
    grep \
    head \
    ip \
    ls \
    mdev \
    mkdir \
    mkfifo \
    mount \
    mv \
    rm \
    sed \
    seq \
    sh \
    sleep \
    tee \
    touch \
    tr \
    udhcpd \
    setsid \
    cttyhack
do
    ln -s busybox "$rootfs_dir/bin/$i"
done
inst inotifywait /bin/inotifywait

make DESTDIR="$PWD/build/qemu/install" -C build/qemu install
inst build/qemu/install/bin/qemu-system-i386 /bin/qemu
inst build/qemu/pc-bios/optionrom/linuxboot.bin /share/qemu/linuxboot.bin
inst build/qemu/pc-bios/vgabios-cirrus.bin /share/qemu/vgabios-cirrus.bin
inst build/qemu/pc-bios/vgabios-stdvga.bin /share/qemu/vgabios-stdvga.bin

inst /usr/bin/xenstore-read /bin/xenstore-read

for i in write watch rm; do
    ln -s xenstore-read "$rootfs_dir/bin/xenstore-$i"
done

# libgcc_s.so.1 is required by xenstore-watch for pthread:
for i in /lib{64,/x86_64-linux-gnu}/libgcc_s.so.1; do
    if [ -e "$i" ]; then
        inst "$i"
        break
    fi
done

inst "rootfs/qemu-ifup" "/etc/qemu-ifup"
inst "rootfs/qemu-ifdown" "/etc/qemu-ifdown"
inst "rootfs/init" "/init"

mkdir $rootfs_dir/lib.new
(find $rootfs_dir/{,usr/}lib{,64} -type f -print0 || true) | xargs -0 mv -t $rootfs_dir/lib.new/
rm -rf $rootfs_dir/{,usr/}lib{,64}
mv $rootfs_dir/lib{.new,}
touch $rootfs_dir/etc/ld.so.conf
/sbin/ldconfig -r $rootfs_dir
ln -s lib $rootfs_dir/lib64

find "$rootfs_dir" -print0 | xargs -0 touch -ch -d @0
(
    cd "$rootfs_dir"
    find . -print0 | \
        LC_ALL=C sort -z | \
        cpio --null -R 0:0 -H newc -o
) | gzip -n -9 > build/rootfs/stubdom-linux-rootfs
