#!/bin/bash

set -e
umask 022

cd "$(dirname "$0")/.."

rootfs_dir="$(pwd)/build/rootfs/dir"

rm -fr "$rootfs_dir"

# Using dracut to gather the shared libraries
# from https://dracut.wiki.kernel.org/index.php/Main_Page
if ! test -x "$DRACUT_INSTALL"; then
    echo DRACUT_INSTALL unset or incorrect >&2
    exit 1
fi

inst() {
    [[ -e "${rootfs_dir}/${2:-$1}" ]] && return 0  # already there
    "$DRACUT_INSTALL" -D "$rootfs_dir" -l "$@"
}

mkdir -p "$rootfs_dir"/{bin,etc,proc/xen,sys,dev,tmp}

echo "Building initrd in $rootfs_dir"
inst build/busybox/busybox /bin/busybox
for i in \
    brctl \
    cat \
    cut \
    grep \
    head \
    ip \
    ls \
    mdev \
    mkdir \
    mkfifo \
    mount \
    mv \
    rm \
    sed \
    seq \
    sh \
    sleep \
    sort \
    tee \
    touch \
    tr \
    udhcpd \
    setsid \
    stty \
    cttyhack
do
    ln -s busybox "$rootfs_dir/bin/$i"
done

if [ -n "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD/build/padist/lib:$PWD/build/padist/lib/pulseaudio"
else
    export LD_LIBRARY_PATH="$PWD/build/padist/lib:$PWD/build/padist/lib/pulseaudio"
fi
inst build/padist/usr/local/bin/pulseaudio /bin/pulseaudio
for mod in build/padist/lib/module-*.so; do
    inst "$mod" /lib/$(basename "$mod")
done

make DESTDIR="$PWD/build/qemu/install" -C build/qemu install
inst build/qemu/install/bin/qemu-system-i386 /bin/qemu
inst build/qemu/pc-bios/optionrom/linuxboot.bin /share/qemu/linuxboot.bin
inst build/qemu/pc-bios/vgabios-cirrus.bin /share/qemu/vgabios-cirrus.bin
inst build/qemu/pc-bios/vgabios-stdvga.bin /share/qemu/vgabios-stdvga.bin

inst xenstore-read /bin/xenstore-read

inst helpers/vchan-socket-proxy /bin/vchan-socket-proxy
inst helpers/add-fd /bin/add-fd

for i in write watch rm ls list; do
    ln -s xenstore-read "$rootfs_dir/bin/xenstore-$i"
done

# libgcc_s.so.1 is required by xenstore-watch for pthread:
for i in /lib{64,/x86_64-linux-gnu}/libgcc_s.so.1; do
    if [ -e "$i" ]; then
        inst "$i"
        break
    fi
done

inst "rootfs/qemu-ifup" "/etc/qemu-ifup"
inst "rootfs/qemu-ifdown" "/etc/qemu-ifdown"
inst "rootfs/init" "/init"

mkdir $rootfs_dir/lib.new
(find $rootfs_dir/{,usr/,usr/local/}lib{,64} -type f -print0 || true) | xargs -0r mv -t $rootfs_dir/lib.new/
rm -rf $rootfs_dir/{,usr/,usr/local/}lib{,64}
IFS=:
for d in $LD_LIBRARY_PATH; do
(find $rootfs_dir/$d -type f -print0 || true) | xargs -0r mv -t $rootfs_dir/lib.new/
rm -rf $rootfs_dir/$d
done
unset IFS
mv $rootfs_dir/lib{.new,}
# possible leftovers from local $LD_LIBRARY_PATH + dracut-install
rm -rf "$rootfs_dir/home"
touch $rootfs_dir/etc/ld.so.conf
/sbin/ldconfig -r $rootfs_dir /lib
ln -s lib $rootfs_dir/lib64

find "$rootfs_dir" -print0 | xargs -0 touch -ch -d @0
(
    cd "$rootfs_dir"
    find . -print0 | \
        LC_ALL=C sort -z | \
        cpio --null -R 0:0 -H newc -o
) | gzip -n -9 > build/rootfs/stubdom-linux-rootfs
