#!/bin/bash

set -e
umask 022

cd "$(dirname "$0")/.."

rootfs_dir="$(pwd)/build/rootfs/dir"

rm -fr "$rootfs_dir"

# Using dracut to gather the shared libraries
# from https://dracut.wiki.kernel.org/index.php/Main_Page
if ! test -x "$DRACUT_INSTALL"; then
  echo DRACUT_INSTALL unset or incorrect >&2
  exit 1
fi
if ! test -x "$GENEXT2FS"; then
  if ! which genext2fs 2>&1 >/dev/null; then
    echo genext2fs not found and GENEXT2FS unset >&2
    exit 1
  fi
else
  function genext2fs(){
    "$GENEXT2FS" "$@"
  }
fi


inst() {
    [[ -e "${rootfs_dir}/${2:-$1}" ]] && return 0  # already there
    "$DRACUT_INSTALL" -D "$rootfs_dir" -l "$@"
}

mkdir -p "$rootfs_dir"/{bin,etc,proc/xen,sys,lib,dev,tmp}

echo "Building initrd in $rootfs_dir"
inst busybox /bin/busybox
make DESTDIR="$rootfs_dir" -C build/qemu install
# this gather libs install on the system for qemu
inst "$rootfs_dir/bin/qemu-system-i386" /bin/qemu
inst "/usr/bin/xenstore-read" "/bin/xenstore-read"
inst "rootfs/qemu-ifup" "/etc/qemu-ifup"
chmod +x "$rootfs_dir/etc/qemu-ifup"
inst "rootfs/init" "/init"
chmod 755 "$rootfs_dir/init"

ln -s busybox "$rootfs_dir/bin/mount"

mkdir $rootfs_dir/lib.new
(find $rootfs_dir/{,usr/}lib{,64} -type f -print0 || true) | xargs -0 mv -t $rootfs_dir/lib.new/
rm -rf $rootfs_dir/{,usr/}lib{,64}
mv $rootfs_dir/lib{.new,}
touch $rootfs_dir/etc/ld.so.conf
/sbin/ldconfig -r $rootfs_dir
ln -s lib $rootfs_dir/lib64

stubdom_disk=build/rootfs/stubdom-disk.img
rm -f "$stubdom_disk"
genext2fs \
  --root "$rootfs_dir" \
  --size-in-blocks $(($(du -s "$rootfs_dir"|cut -f1)+2000)) \
  --reserved-percentage 0 \
  --squash \
  "$stubdom_disk"
